const route_list = {
    "505":{"route": "505","color": "#DA2128", "stops": [
        "Sam Shing",
        "Siu Lun",
        "On Ting",
        "Town Centre",
        "Tuen Mun",
        "Kin On",
        "Shan King (South)",
        "Shan King (North)",
        "Ming Kum",
        "Shek Pai",
        "San Wai",
        "Leung King",
        "Tin King",
        "Kin Sang",
        "Ching Chung",
        "Kei Lun",
        "Siu Hong"
    ]},
    "507":{"route": "507","color": "#00A54F", "stops": [
        "Tuen Mun Ferry Pier",
        "Siu Hei",
        "Tuen Mun Swimming Pool",
        "Goodview Garden",
        "Siu Lun",
        "On Ting",
        "Town Centre",
        "Tuen Mun",
        "Ho Tin",
        "Choy Yee Bridge",
        "Ngan Wai",
        "Tai Hing (South)",
        "Tai Hing (North)",
        "San Wai",
        "Leung King",
        "Tin King"
    ]},
    "610":{"route": "610","color": "#541912","stops": [
        "Tuen Mun Ferry Pier",
        "Melody Garden",
        "Butterfly",
        "Light Rail Depot",
        "Lung Mun",
        "Tsing Shan Tsuen",
        "Tsing Wun",
        "Ming Kum",
        "Shek Pai",
        "Tai Hing (North)",
        "Tai Hing (South)",
        "Ngan Wai",
        "Affluence",
        "Tuen Mun Hospital",
        "Siu Hong",
        "Lam Tei",
        "Nai Wai",
        "Chung Uk Tsuen",
        "Hung Shui Kiu",
        "Tong Fong Tsuen",
        "Ping Shan",
        "Shui Pin Wai",
        "Fung Nin Road",
        "Hong Lok Road",
        "Tai Tong Road",
        "Yuen Long"
    ]},
    "614":{"route": "614","color": "#15C0F2","stops": [
        "Tuen Mun Ferry Pier",
        "Siu Hei",
        "Tuen Mun Swimming Pool",
        "Goodview Garden",
        "Siu Lun",
        "On Ting",
        "Town Centre",
        "Pui To",
        "Hoh Fuk Tong",
        "San Hui",
        "Prime View",
        "Fung Tei",
        "Siu Hong",
        "Lam Tei",
        "Nai Wai",
        "Chung Uk Tsuen",
        "Hung Shui Kiu",
        "Tong Fong Tsuen",
        "Ping Shan",
        "Shui Pin Wai",
        "Fung Nin Road",
        "Hong Lok Road",
        "Tai Tong Road",
        "Yuen Long"
    ]},
    "614P":{"route": "614P","color": "#F4939A","stops": [
        "Tuen Mun Ferry Pier",
        "Siu Hei",
        "Tuen Mun Swimming Pool",
        "Goodview Garden",
        "Siu Lun",
        "On Ting",
        "Town Centre",
        "Pui To",
        "Hoh Fuk Tong",
        "San Hui",
        "Prime View",
        "Fung Tei",
        "Siu Hong",
    ]},
    "615":{"route": "615","color": "#FFDC01","stops": [
        "Tuen Mun Ferry Pier",
        "Melody Garden",
        "Butterfly",
        "Light Rail Depot",
        "Lung Mun",
        "Tsing Shan Tsuen",
        "Tsing Wun",
        "Ming Kum",
        "Shek Pai",
        "San Wai",
        "Leung King",
        "Tin King",
        "Kin Sang",
        "Ching Chung",
        "Siu Hong",
        "Lam Tei",
        "Nai Wai",
        "Chung Uk Tsuen",
        "Hung Shui Kiu",
        "Tong Fong Tsuen",
        "Ping Shan",
        "Shui Pin Wai",
        "Fung Nin Road",
        "Hong Lok Road",
        "Tai Tong Road",
        "Yuen Long"
    ]},
    "615P":{"route": "615P","color": "#016584","stops": [
        "Tuen Mun Ferry Pier",
        "Melody Garden",
        "Butterfly",
        "Light Rail Depot",
        "Lung Mun",
        "Tsing Shan Tsuen",
        "Tsing Wun",
        "Ming Kum",
        "Shek Pai",
        "San Wai",
        "Leung King",
        "Tin King",
        "Kin Sang",
        "Ching Chung",
        "Siu Hong",
    ]},
    "705":{"route": "705","color": "#71BF44","stops":[
        "Tin Shui Wai",
        "Tin Tsz",
        "Tin Wu",
        "Ginza",
        "Tin Wing",
        "Tin Yuet",
        "Tin Sau",
        "Wetland Park",
        "Tin Heng",
        "Tin Yat",
        "Tin Fu",
        "Chung Fu",
        "Tin Shui",
        "Locwood",
        "Tin Yiu"
    ]},
    "706":{"route": "706","color": "#B279B4","stops":[
        "Tin Shui Wai",
        "Tin Yiu",
        "Locwood",
        "Tin Shui",
        "Chung Fu",
        "Tin Fu",
        "Tin Yat",
        "Tin Heng",
        "Wetland Park",
        "Tin Sau",
        "Tin Yuet",
        "Tin Wing",
        "Ginza",
        "Tin Wu",
        "Tin Tsz"
    ]},
    "751":{"route": "751","color": "#F58220","stops":[
        "Yau Oi",
        "On Ting",
        "Town Centre",
        "Tuen Mun",
        "Ho Tin",
        "Choy Yee Bridge",
        "Affluence",
        "Tuen Mun Hospital",
        "Siu Hong",
        "Lam Tei",
        "Nai Wai",
        "Chung Uk Tsuen",
        "Hung Shui Kiu",
        "Hang Mei Tsuen",
        "Tin Shui Wai",
        "Tin Tsz",
        "Tin Wu",
        "Ginza",
        "Tin Wing",
        "Chestwood",
        "Chung Fu",
        "Tin Fu",
        "Tin Yat"
    ]},
    "751P":{"route": "751P","color": "#F58220","stops":[
        "Tin Shui Wai",
        "Tin Tsz",
        "Tin Wu",
        "Ginza",
        "Tin Wing",
        "Chestwood",
        "Chung Fu",
        "Tin Fu",
        "Tin Yat"
    ]},
    "761P":{"route": "761P","color": "#6E2C91", "stops":[
        "Yuen Long",
        "Tai Tong Road",
        "Hong Lok Road",
        "Fung Nin Road",
        "Shui Pin Wai",
        "Ping Shan",
        "Tong Fong Tsuen",
        "Hang Mei Tsuen",
        "Tin Yiu",
        "Locwood",
        "Tin Shui",
        "Chung Fu",
        "Tin Fu",
        "Tin Yat"
    ]},
}

export default route_list